package context

import (
	"asher/internal/models"
)

var test_1_tableName = "student_enrollments"
var test_1_columnInputArray = []models.Column{

	{
		Name:               "id",
		ColType:            "bigInteger",
		GenerationStrategy: "auto_increment",
		DefaultVal:         "",
		Table:              "",
		Validations:        "unique:id",
		Index:              false,
		Allowed:            nil,
		Hidden:             true,
		Guarded:            true,
		Primary:            true,
		Unique:             false,
		Nullable:           false,
		OnDelete:           "",
	},
	{
		Name:               "id_2",
		ColType:            "",
		GenerationStrategy: "uuid",
		DefaultVal:         "",
		Table:              "",
		Validations:        "",
		Index:              false,
		Allowed:            nil,
		Hidden:             false,
		Guarded:            true,
		Primary:            true,
		Unique:             false,
		Nullable:           false,
		OnDelete:           "",
	},
	{
		Name:               "name",
		ColType:            "string",
		GenerationStrategy: "",
		DefaultVal:         "",
		Table:              "",
		Validations:        "",
		Index:              false,
		Allowed:            nil,
		Hidden:             true,
		Guarded:            false,
		Primary:            false,
		Unique:             false,
		Nullable:           false,
		OnDelete:           "",
	},
	{
		Name:               "description",
		ColType:            "string",
		GenerationStrategy: "",
		DefaultVal:         "default description",
		Table:              "",
		Validations:        "",
		Index:              false,
		Allowed:            nil,
		Hidden:             false,
		Guarded:            false,
		Primary:            false,
		Unique:             true,
		Nullable:           true,
		OnDelete:           "",
	},
	{
		Name:               "order_id",
		ColType:            "bigInteger",
		GenerationStrategy: "",
		DefaultVal:         "0",
		Table:              "orders:id",
		Validations:        "",
		Index:              true,
		Allowed:            nil,
		Hidden:             false,
		Guarded:            false,
		Primary:            false,
		Unique:             true,
		Nullable:           true,
		OnDelete:           "cascade",
	},
	{
		Name:               "dummy_column",
		ColType:            "enum",
		GenerationStrategy: "",
		DefaultVal:         "",
		Table:              "",
		Validations:        "",
		Index:              false,
		Allowed:            []string{"a", "asas", "saDASD"},
		Hidden:             true,
		Guarded:            false,
		Primary:            false,
		Unique:             true,
		Nullable:           true,
		OnDelete:           "",
	},
}

var test_1_fillableExpectedOutput = []string{`"id"`, `"id_2"`}
var test_1_hiddenExpectedOutput = []string{`"id"`, `"name"`, `"dummy_column"`}
